runtime: java8
env: flex
runtime_config:
  jdk: openjdk8
  
env_variables:
  SPRING_PROFILES_ACTIVE: "production"
handlers:
- url: /.*
  script: this field is required, but ignored
manual_scaling:
  instances: 1